name: Test
run-name: test
on: [push]

jobs:
  test-linux-clang:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-20251208
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y clang cmake git nodejs ninja-build pkg-config

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -S . -B out -GNinja --preset ci-test-clang
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          ctest -V -C DebugSan

  test-linux-gcc:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-20251208
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential cmake git nodejs ninja-build pkg-config

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -S . -B out -GNinja --preset ci-test-gcc
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          ctest -V -C DebugSan

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -S . -B out --preset ci-test-windows
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          ctest -V -C DebugSan