name: Test
run-name: test
on: [push]

jobs:
  test-linux-clang:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-20251208
    strategy:
      matrix:
        unity: ["ON", "OFF"]
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y clang cmake git nodejs ninja-build pkg-config

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -S . -B out -GNinja --preset ci-test-clang -DCMAKE_UNITY_BUILD=${{ matrix.unity }}
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          ctest -V -C DebugSan

  test-linux-gcc:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-20251208
    strategy:
      matrix:
        unity: ["ON", "OFF"]
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential cmake git nodejs ninja-build pkg-config

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -S . -B out -GNinja --preset ci-test-gcc -DCMAKE_UNITY_BUILD=${{ matrix.unity }}
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          ctest -V -C DebugSan

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        unity: ["ON", "OFF"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup env
        shell: pwsh
        run: |
          # Append the location of the clang_rt.asan DLL to the PATH so that
          # the test exe can run
          function Find-Dirx64 {
            try {
              # Github runner
              $Dirx64 = Get-ChildItem -Path 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/' -Recurse -Filter "Hostx64" -ErrorAction Stop
              return $Dirx64
            } catch {
              # Self-hosted runner
              $Dirx64 = Get-ChildItem -Path 'C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/' -Recurse -Filter "Hostx64"
              return $Dirx64
            }
          }
          $Dirx64 = Find-Dirx64
          $Dll = Get-ChildItem -Path $Dirx64.FullName -Recurse -Filter "clang_rt.asan_dbg_dynamic-x86_64.dll"
          $DllDir = $Dll.Directory
          Write-Output $DllDir.FullName >> $env:GITHUB_PATH

      - name: Configure
        run: |
          cmake -S . -B out --preset ci-test-windows -DCMAKE_UNITY_BUILD=${{ matrix.unity }}
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          ctest -V -C DebugSan
  test-emscripten:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:4.0.23
    strategy:
      matrix:
        unity: ["ON", "OFF"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure
        run: |
          emcmake cmake -S . -B out --preset ci-test-nodejs -DCMAKE_UNITY_BUILD=${{ matrix.unity }}
      - name: Build
        run: |
          cmake --build out --config DebugSan
      - name: Test
        run: |
          cd out
          node src/std/std-tests.js
